### ISSUE TITLE
Fix #

### ISSUE THREAD

**Issue by ghost** [int-e/bitch#2]
* <small># should definitely be fixed, to be fully compatible with the spec. `#]1` does the same thing as ]1. Hypothetically, this interpreter might do something other than this.<small>

**Comment by int-e** [comment]
Is there a better specification for this than https://esolangs.org/wiki/Bitch#I.2FO_Instructions? That source refers to `number` as a constant; the meaning of `number` is extended in the next section.

In either case, in the reference implementation `#]1` clears the storage, whereas `]1` does not.

P.S. That extra effect of clearing the storage may be useful, so I've decided to conform to the reference implementation. I had previously thought that there was no point in using `#` without a literal.
