### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [int-e/bitch#4]
There is a tiny issue in your implementation: the Haskell implementation mentions a "difference" that you've already fixed:
```haskell
-- - (fix) input in chained instruction reads from same line as unchained
--   instructions
```

**Comment by int-e** [comment]
Thanks! This comment alludes to a bug in the reference implementation. But I forgot to remove in 7e18d80d5e10ee1bfadba5dd99d1197119e000b8.
